services:
  mysql:
    image: 'mysql:9.1.0'
    environment:
      - 'MYSQL_DATABASE=forum'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  redis:
    image: 'redis:7.4.2'
    container_name: redis-local
    ports:
      - '6379:6379'