spring:
  docker:
    compose:
      file: docker-compose.dev.yml
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqlserver.example:3306/forum
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    type: redis
  redis:
    host: redisserver.example
    port: 6379
    password: ${REDIS_PASSWORD}
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 362f41a3e51994
    password: 3ea96e8b3235e8
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: dpHA5A$z7ClCoaM%3DT4zfZzEZ0rf4TPY0mNTgj%GP5NXDwTVB#i5HYxSeejmIpw*MOO9^t&a9PhV1wJT*MdifGT*dCkL1Miala6zs2W#V2xBaU9@s1*TRUHRZxflaG3
