spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
jwt:
  secret: dpHA5A$z7ClCoaM%3DT4zfZzEZ0rf4TPY0mNTgj%GP5NXDwTVB#i5HYxSeejmIpw*MOO9^t&a9PhV1wJT*MdifGT*dCkL1Miala6zs2W#V2xBaU9@s1*TRUHRZxflaG3